// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB03WdurvbVBoOZZbUljq-1rHUVOGSCUxc',
    appId: '1:882661304446:web:47d9cf911d0ce40199502f',
    messagingSenderId: '882661304446',
    projectId: 'e-refuge',
    authDomain: 'e-refuge.firebaseapp.com',
    storageBucket: 'e-refuge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkz8r6IPs6VFNbEzP5JKJhJL8CP69HwmQ',
    appId: '1:882661304446:android:d4549040e9a9710599502f',
    messagingSenderId: '882661304446',
    projectId: 'e-refuge',
    storageBucket: 'e-refuge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Qs9ITYFNIdZixs9wKScP_dnqt57u2-k',
    appId: '1:882661304446:ios:35f897c93a26b97499502f',
    messagingSenderId: '882661304446',
    projectId: 'e-refuge',
    storageBucket: 'e-refuge.appspot.com',
    iosClientId: '882661304446-bdfk9denj2mpl6hg781eih15gu6bpeua.apps.googleusercontent.com',
    iosBundleId: 'com.refuge.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Qs9ITYFNIdZixs9wKScP_dnqt57u2-k',
    appId: '1:882661304446:ios:35f897c93a26b97499502f',
    messagingSenderId: '882661304446',
    projectId: 'e-refuge',
    storageBucket: 'e-refuge.appspot.com',
    iosClientId: '882661304446-bdfk9denj2mpl6hg781eih15gu6bpeua.apps.googleusercontent.com',
    iosBundleId: 'com.refuge.app',
  );
}
